#!/usr/bin/env node

/* jshint node: true */

var sqlpatch = require('./src/sqlpatch').sqlpatch;
var nopt = require('nopt');
var glob = require("glob");

var options = nopt({
    dialect: [String],
    schema: [String],
    table: [String],
}, {}, process.argv, 2);

process.stdout.write(sqlpatch(options.argv.remain.reduce(function(list, src) {
    return list.concat(glob.sync(src));
}, []), options));