#!/usr/bin/env node

/* jshint node: true */

var sqlpatch = require('./src/sqlpatch');
var nopt = require('nopt');

var options = nopt({}, {}, process.argv, 2);

sqlpatch(options.argv.remain, process.stdout, options);