#!/usr/bin/env node

/* jshint node: true */

var sqlpatch = require('./src/sqlpatch');
var nopt = require('nopt');
var glob = require("glob");

var options = nopt({}, {}, process.argv, 2);

sqlpatch(options.argv.remain.reduce(function(list, src) {
    return list.concat(glob.sync(src));
}, []), process.stdout, options);