CREATE TABLE [Projects] (
    [ProjectKey]                SMALLINT         IDENTITY (1, 1) NOT NULL,
    [ProjectID]                 UNIQUEIDENTIFIER CONSTRAINT [DF_Projects_ProjectID] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [ProjectName]               NVARCHAR (100)   NOT NULL,
    [ProjectDescription]        NVARCHAR (MAX)   NULL,
    [CreatedUTC]                SMALLDATETIME    NOT NULL,
    [ModifiedUTC]               SMALLDATETIME    NOT NULL,
    [LastProjectResultKey]      SMALLINT         CONSTRAINT [DF_Projects_LastProjectResultKey] DEFAULT ((0)) NOT NULL,
    [ProjectResultCount]        SMALLINT         CONSTRAINT [DF_Projects_ProjectResultCount] DEFAULT ((0)) NOT NULL,
    [LastInspectionGroupKey]    TINYINT          CONSTRAINT [DF_Projects_LastInspectionGroupKey] DEFAULT ((0)) NOT NULL,
    [InspectionGroupCount]      TINYINT          CONSTRAINT [DF_Projects_InspectionGroupCount] DEFAULT ((0)) NOT NULL,
    [LastInspectionSerieKey]    TINYINT          CONSTRAINT [DF_Projects_LastInspectionSerieKey] DEFAULT ((0)) NOT NULL,
    [InspectionSerieCount]      TINYINT          CONSTRAINT [DF_Projects_InspectionSerieCount] DEFAULT ((0)) NOT NULL,
    [LastInspectionCategoryKey] TINYINT          CONSTRAINT [DF_Projects_LastInspectionCategoryKey] DEFAULT ((0)) NOT NULL,
    [InspectionCategoryCount]   TINYINT          CONSTRAINT [DF_Projects_InspectionCategoryCount] DEFAULT ((0)) NOT NULL,
    [LastInspectionKey]         SMALLINT         CONSTRAINT [DF_Projects_LastInspectionKey] DEFAULT ((0)) NOT NULL,
    [InspectionCount]           SMALLINT         CONSTRAINT [DF_Projects_InspectionCount] DEFAULT ((0)) NOT NULL,
    [ObjectTypeCount]           SMALLINT         CONSTRAINT [DF_Projects_ObjectTypeCount] DEFAULT ((0)) NOT NULL,
    [LastObjectKey]             SMALLINT         CONSTRAINT [DF_Projects_LastObjectKey] DEFAULT ((0)) NOT NULL,
    [ProjectObjectCount]        SMALLINT         CONSTRAINT [DF_Projects_ProjectObjectCount] DEFAULT ((0)) NOT NULL,
    [LastIdentifierPropertyKey] SMALLINT         DEFAULT ((0)) NOT NULL,
    [ReportTypeSeed]            TINYINT          CONSTRAINT [DF_Projects_ReportTypeSeed] DEFAULT ((0)) NOT NULL,
    [ReportTypeCount]           TINYINT          CONSTRAINT [DF_Projects_ReportTypeCount] DEFAULT ((0)) NOT NULL,
    [PropertyTypeCount]         SMALLINT         DEFAULT ((0)) NOT NULL,
    [Timestamp] TIMESTAMP NOT NULL,
    [ProjectCode] VARCHAR(24) NULL,
    CONSTRAINT [PK_Projects] PRIMARY KEY NONCLUSTERED ([ProjectKey] ASC),
    CONSTRAINT [CK_Projects_InspectionCategoryCount] CHECK ([InspectionCategoryCount]>=(0)),
    CONSTRAINT [CK_Projects_InspectionCount] CHECK ([InspectionCount]>=(0)),
    CONSTRAINT [CK_Projects_InspectionGroupCount] CHECK ([InspectionGroupCount]>=(0)),
    CONSTRAINT [CK_Projects_InspectionSerieCount] CHECK ([InspectionSerieCount]>=(0)),
    CONSTRAINT [CK_Projects_ObjectTypeCount] CHECK ([ObjectTypeCount]>=(0)),
    CONSTRAINT [CK_Projects_ProjectKey] CHECK ([ProjectKey]>(0)),
    CONSTRAINT [CK_Projects_ProjectName] CHECK (ltrim(rtrim([ProjectName]))=[ProjectName] AND [ProjectName]<>''),
    CONSTRAINT [CK_Projects_ProjectObjectCount] CHECK ([ProjectObjectCount]>=(0)),
    CONSTRAINT [CK_Projects_ProjectResultCount] CHECK ([ProjectResultCount]>=(0)),
    CONSTRAINT [CK_Projects_PropertyTypeCount] CHECK ([PropertyTypeCount]>=(0)),
    CONSTRAINT [CK_ReportType_ReportTypeCount] CHECK ([ReportTypeCount]>=(0)),
    CONSTRAINT [CK_ReportType_ReportTypeSeed] CHECK ([ReportTypeSeed]>=(0)),
    CONSTRAINT [UQ_Projects_ProjectID] UNIQUE NONCLUSTERED ([ProjectID] ASC),
    CONSTRAINT [UQ_Projects_ProjectName] UNIQUE CLUSTERED ([ProjectName] ASC)
);

