-- generated by {{&pkg.name}} {{&pkg.version}}

CREATE TABLE IF NOT EXISTS ___patches(
    name VARCHAR(100) PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    checksum CHAR(40) NULL
);



{{#patches}}

-- {{&name}} - {{&file}}

DO $___patch_{{&number}}$
BEGIN

    IF EXISTS (SELECT 1 FROM ___patches WHERE name = '{{&name}}') THEN
        RETURN;
    END IF;

    {{#dependencies}}
    IF NOT EXISTS (SELECT 1 FROM ___patches WHERE name = '{{&name}}' AND '{{&checksum}}' IN (checksum, '')) THEN
        RAISE EXCEPTION 'missing dependency or invalid checksum: {{&name}}';
    END IF;
    {{/dependencies}}

    RAISE NOTICE '{{&name}}';

{{&content}}

    INSERT INTO ___patches (name, checksum) VALUES('{{&name}}', '{{&checksum}}');

END
$___patch_{{&number}}$ LANGUAGE plpgsql;

{{/patches}}