/* jshint node: true */

module.exports = sqlpatch;

var fs = require('fs');
var path = require('path');
var pkg = require('../package');
var toposort = require('toposort');
var extend = require('extend');

function sqlpatch(fileList, writer, options) {

    options = extend({
        dialect: 'postgres'
    }, options);

    if (!~['postgres', 'sqlserver'].indexOf(options.dialect)) throw new Error("unknown dialect: '" + options.dialect + "'");

    var fileInfoList = fileList.map(readFileInfo);
    var fileInfoMap = fileInfoList.reduce(function(map, item) {
        var name;
        if ('name' in item.properties && item.properties.name.length >= 1) name = item.properties.name[0];
        else name = path.basename(item.file, '.sql');
        if (name in map) throw new Error("duplicate name '" + name + "'");
        map[name] = item;
        return map;
    }, {});

    var nameList = Object.keys(fileInfoMap);
    var nameEdgeList = nameList.reduce(function(list, name) {
        var fileInfoItem = fileInfoMap[name];
        if ('require' in fileInfoItem.properties) fileInfoItem.properties.require.forEach(function(dependencyName) {
            list.push([name, dependencyName]);
        });
        return list;
    }, []);

    var dependencyList = toposort.array(nameList, nameEdgeList);
    dependencyList.reverse();

    writeline(
        "-- generated by " + pkg.name + " " + pkg.version + ""
    );
    writeline();
    writeline();
    writeline();

    switch (options.dialect) {
        case "postgres":
            writeline(
                "CREATE TABLE IF NOT EXISTS ___patches(name VARCHAR(100) PRIMARY KEY, created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);"
            );
            break;

        case "sqlserver":
            writeline(
                "IF OBJECT_ID('___patches', 'U') IS NULL",
                "CREATE TABLE dbo.___patches(name VARCHAR(100) PRIMARY KEY, created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                ";"
            );
            break;
    }
    writeline();
    writeline();
    writeline();


    dependencyList.forEach(function(name, index) {
        var fileInfoItem = fileInfoMap[name];
        var number = index + 1;

        writeline("-- " + name + ": " + fileInfoItem.file);

        switch (options.dialect) {
            case "postgres":
                writeline(
                    "DO $___patch_" + number + "$",
                    "BEGIN"
                );
                writeline(
                    "IF EXISTS (SELECT 1 FROM ___patches WHERE name = '" + name + "') THEN RETURN; END IF;"
                );
                break;

            case "sqlserver":
                writeline(
                    "IF NOT EXISTS (SELECT 1 FROM ___patches WHERE name = '" + name + "')",
                    "BEGIN TRY",
                    "BEGIN TRANSACTION;"
                );
                break;
        }

        if ('require' in fileInfoItem.properties) fileInfoItem.properties.require.forEach(function(dependencyName) {
            switch (options.dialect) {
                case "postgres":
                    writeline(
                        "IF NOT EXISTS (SELECT 1 FROM ___patches WHERE name = '" + dependencyName + "')",
                        "THEN RAISE EXCEPTION 'missing dependency: " + dependencyName + "';",
                        "END IF;"
                    );
                    break;

                case "sqlserver":
                    writeline(
                        "IF NOT EXISTS (SELECT 1 FROM ___patches WHERE name = '" + dependencyName + "')",
                        "THROW 50000, 'missing dependency: " + dependencyName + "', 0;"
                    );
                    break;
            }
        });

        writeline();
        writeline(fileInfoItem.content);
        writeline();

        switch (options.dialect) {
            case "postgres":
                writeline(
                    "INSERT INTO ___patches (name) VALUES('" + name + "');"
                );
                writeline(
                    "END",
                    "$___patch_" + number + "$ LANGUAGE plpgsql;"
                );
                break;

            case "sqlserver":
                writeline(
                    "INSERT INTO ___patches (name) VALUES('" + name + "');"
                );
                writeline(
                    "COMMIT TRANSACTION;",
                    "END TRY",
                    "BEGIN CATCH",
                    "ROLLBACK TRANSACTION;",
                    "THROW;",
                    "END CATCH;"
                );
                break;
        }

        writeline();
        writeline();
        writeline();
    });

    function writeline() {
        writer.write(Array.prototype.slice.apply(arguments).join('\n') + '\n');
    }

}

function readFileInfo(file) {
    var content = fs.readFileSync(file).toString().replace(/(^\s+|\s+$|)/g, "");
    var properties = readProperties(content);
    return {
        file: file,
        content: content,
        properties: properties,
    };
}

function readProperties(content) {
    var result = {};
    var match;
    var re = /^\s*\-\-\s*@(.+?)\s+(.+?)\s*$/gm;
    while ((match = re.exec(content))) {
        if (match[1] in result) result[match[1]].push(match[2]);
        else result[match[1]] = [match[2]];
    }
    return result;
}