-- generated by {{ pkg.name }} {{ pkg.version }}

IF OBJECT_ID('___patches', 'U') IS NULL
BEGIN
    CREATE TABLE ___patches(
        name VARCHAR(100) PRIMARY KEY,
        created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        checksum CHAR(40) NULL
    )
END
GO


{{#patches}}

-- {{&name}} - {{&file}}

IF NOT EXISTS (SELECT 1 FROM ___patches WHERE name = '{{&name}}')
BEGIN TRY
    BEGIN TRANSACTION;

    {{#dependencies}}
    IF NOT EXISTS (SELECT 1 FROM ___patches WHERE name = '{{&name}}' AND '{{&checksum}}' IN (checksum, ''))
    BEGIN
        THROW 50000, 'missing dependency or invalid checksum: {{&name}}', 0;
    END
    {{/dependencies}}

{{&content}}

    INSERT INTO ___patches (name, checksum) VALUES('{{&name}}', '{{checksum}}');

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO

{{/patches}}