-- generated by {{ pkg.name }} {{ pkg.version }}

IF OBJECT_ID('___patches', 'U') IS NULL
BEGIN
    CREATE TABLE ___patches(
        name VARCHAR(100) PRIMARY KEY,
        created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
END
GO


{{#patches}}

-- {{&name}} - {{&file}}

IF NOT EXISTS (SELECT 1 FROM ___patches WHERE name = '{{&name}}')
BEGIN TRY
    BEGIN TRANSACTION;


    {{#properties.require}}
    IF NOT EXISTS (SELECT 1 FROM ___patches WHERE name = '{{&.}}')
    BEGIN
        THROW 50000, 'missing dependency: {{&.}}', 0;
    END
    {{/properties.require}}

    {{&content}}

    INSERT INTO ___patches (name) VALUES('{{&name}}');

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO

{{/patches}}